#' Build a Dataset submission row from a Trio object
#'
#' This helper is the first step in the new submission workflow. It does not
#' upload anything and does not modify the existing writeCTD() path.
#'
#' @param trio A `Trio` object.
#' @param name Dataset name for submission. Defaults to the existing Trio name,
#'   falling back to `trio$dataSourceID` when needed.
#' @param dataType One of `"omics"` or `"clinical"`.
#' @param dataModality One of `"genomics"`, `"transcriptomics"`,
#'   `"epigenomics"`, `"proteomics"`, `"metabolomics"`, `"patient"`,
#'   or `"other"`.
#' @param technology Free-text technology description.
#' @param description Dataset description. Defaults to `trio$description` if
#'   present.
#' @param doi DOI reference for the dataset.
#' @param tissue Free-text tissue label.
#' @param organism Free-text organism label.
#' @param status One of `"healthy"`, `"diseased"`, `"developmental"`,
#'   or `"other"`.
#'
#' @return A one-row `data.frame` matching the proposed `Dataset` table schema.
#'   `datasetID` is left as `NA` because it is expected to be generated by the
#'   submission backend.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' buildDatasetSubmission(
#'   trio,
#'   dataType = "omics",
#'   dataModality = "transcriptomics",
#'   technology = "RNA-seq",
#'   tissue = "blood",
#'   status = "healthy"
#' )
#' @export
buildDatasetSubmission <- function(
    trio,
    name = private_submission_dataset_name(trio),
    dataType,
    dataModality,
    technology,
    description = trio$description,
    doi = NA_character_,
    organism = NA_character_,
    tissue,
    status
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (is.null(name) || !nzchar(name)) {
    cli::cli_abort(
      "{.arg name} must be provided when the Trio does not already have a usable name."
    )
  }

  private_validate_submission_choice(
    value = dataType,
    arg = "dataType",
    choices = c("omics", "clinical")
  )
  private_validate_submission_choice(
    value = dataModality,
    arg = "dataModality",
    choices = c(
      "genomics",
      "transcriptomics",
      "epigenomics",
      "proteomics",
      "metabolomics",
      "patient",
      "other"
    )
  )
  private_validate_submission_choice(
    value = status,
    arg = "status",
    choices = c(
      "healthy",
      "diseased",
      "developmental",
      "other"
    )
  )

  if (missing(technology) || is.null(technology) || !nzchar(technology)) {
    cli::cli_abort("{.arg technology} must be a non-empty string.")
  }

  if (missing(tissue) || is.null(tissue) || !nzchar(tissue)) {
    cli::cli_abort("{.arg tissue} must be a non-empty string.")
  }

  if (is.null(description) || !nzchar(description)) {
    cli::cli_abort(
      "{.arg description} must be provided when the Trio does not already have a description."
    )
  }

  numSamples <- private_get_submission_num_samples(trio$data)

  data.frame(
    datasetID = NA_character_,
    name = as.character(name),
    source = private_submission_chr(trio$dataSource),
    datasourceID = private_submission_chr(trio$dataSourceID),
    dataType = as.character(dataType),
    dataModality = as.character(dataModality),
    technology = as.character(technology),
    description = as.character(description),
    doi = private_submission_chr(doi),
    numSamples = numSamples,
    organism = private_submission_chr(organism),
    tissue = as.character(tissue),
    status = as.character(status),
    stringsAsFactors = FALSE
  )
}

#' Collect Dataset submission metadata interactively
#'
#' This helper gathers the dataset-level fields needed for the `Dataset` table.
#' It reuses `Trio` metadata when already available and only prompts for the
#' remaining values in interactive sessions.
#'
#' @param trio A `Trio` object.
#' @param defaults Optional named list of pre-filled values. Any non-`NULL`
#'   value here bypasses the interactive prompt for that field.
#'
#' @return A named list ready to pass as `dataset_args` to
#'   `buildDatasetSubmission()`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' collectDatasetSubmissionInfo(
#'   trio,
#'   defaults = list(
#'     dataType = "omics",
#'     dataModality = "transcriptomics",
#'     technology = "RNA-seq",
#'     tissue = "blood",
#'     status = "healthy"
#'   )
#' )
#' @export
collectDatasetSubmissionInfo <- function(
    trio,
    defaults = list()
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (!is.list(defaults)) {
    cli::cli_abort("{.arg defaults} must be a named list.")
  }

  data_type <- private_collect_submission_choice(
    value = defaults$dataType,
    choices = c("omics", "clinical"),
    title = "Please choose data type"
  )
  data_modality <- private_collect_submission_choice(
    value = defaults$dataModality,
    choices = c(
      "genomics",
      "transcriptomics",
      "epigenomics",
      "proteomics",
      "metabolomics",
      "patient",
      "other"
    ),
    title = "Please choose data modality"
  )
  status <- private_collect_submission_choice(
    value = defaults$status,
    choices = c(
      "healthy",
      "diseased",
      "developmental",
      "other"
    ),
    title = "Please choose dataset status"
  )

  list(
    name = private_collect_submission_text(
      value = defaults$name,
      prompt = "Dataset name",
      fallback = private_submission_dataset_name(trio)
    ),
    dataType = data_type,
    dataModality = data_modality,
    technology = private_collect_submission_text(
      value = defaults$technology,
      prompt = "Please describe the technology of this dataset",
      required = TRUE
    ),
    description = private_collect_submission_text(
      value = defaults$description,
      prompt = "Dataset description",
      fallback = trio$description,
      required = TRUE
    ),
    doi = private_collect_submission_text(
      value = defaults$doi,
      prompt = "Please describe the DOI of this dataset",
      required = FALSE
    ),
    organism = private_collect_submission_text(
      value = defaults$organism,
      prompt = "Please describe the Organism of this dataset",
      required = FALSE
    ),
    tissue = private_collect_submission_text(
      value = defaults$tissue,
      prompt = "Please describe the Tissue of this dataset",
      required = TRUE
    ),
    status = status
  )
}

#' Prepare Trio files and download metadata for submission
#'
#' This helper reuses the good parts of the old `writeCTD()` workflow for the
#' new submission path. It can either save dataset/evidence files locally so
#' the user can upload them, or reuse an existing downloadable source already
#' attached to the `Trio`.
#'
#' @param trio A `Trio` object.
#' @param name Dataset name used for generated filenames. Defaults to
#'   `trio$name`.
#' @param outputDir Directory for generated `.rds` files. Defaults to `"."`.
#' @param saveData Logical indicating whether to save `trio$data` to an RDS
#'   file. If `NULL` and interactive, the user is prompted.
#' @param saveEvidence Logical indicating whether to save all supporting
#'   evidence to a single RDS file. If `NULL` and interactive, defaults to
#'   `TRUE`.
#' @param useExistingSource Logical indicating whether to keep using
#'   `trio$dataSource`/`trio$dataSourceID` rather than preparing uploaded files.
#'   If `NULL` and interactive, the user is prompted when an existing source is
#'   available.
#' @param figshareUrl Optional Figshare URL to verify against prepared files.
#' @param datasetFileName Optional dataset filename to match inside the Figshare
#'   article.
#' @param evidenceFileName Optional evidence filename to match inside the
#'   Figshare article.
#' @param verifyFigshare Logical; if `TRUE`, verify the prepared files against
#'   the Figshare article metadata.
#' @param skipMd5Check Logical; if `TRUE`, allow verification without MD5
#'   matching.
#'
#' @return A named list describing the saved files and/or reusable download
#'   sources for dataset and evidence.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' files <- prepareTrioSubmissionFiles(
#'   trio,
#'   outputDir = tempdir(),
#'   saveData = TRUE,
#'   saveEvidence = TRUE,
#'   useExistingSource = FALSE
#' )
#' names(files)
#' @export
prepareTrioSubmissionFiles <- function(
    trio,
    name = trio$name,
    outputDir = ".",
    saveData = NULL,
    saveEvidence = NULL,
    useExistingSource = NULL,
    figshareUrl = NULL,
    datasetFileName = NULL,
    evidenceFileName = NULL,
    verifyFigshare = FALSE,
    skipMd5Check = FALSE
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (is.null(name) || !nzchar(name)) {
    cli::cli_abort(
      "{.arg name} must be provided when the Trio does not already have a name."
    )
  }

  if (!dir.exists(outputDir)) {
    cli::cli_abort("{.arg outputDir} must be an existing directory.")
  }

  existing_source_available <- !is.null(trio$dataSource) &&
    nzchar(as.character(trio$dataSource)) &&
    !is.null(trio$dataSourceID) &&
    nzchar(as.character(trio$dataSourceID))

  if (is.null(useExistingSource)) {
    if (interactive() && existing_source_available) {
      useExistingSource <- utils::askYesNo(
        "Use the existing Trio download source instead of preparing a dataset file?"
      )
    } else {
      useExistingSource <- existing_source_available
    }
  }

  if (is.null(saveData)) {
    if (interactive() && !useExistingSource) {
      saveData <- utils::askYesNo(
        "Do you want to save the data to an RDS file in the selected output directory?"
      )
    } else {
      saveData <- !useExistingSource
    }
  }

  if (is.null(saveEvidence)) {
    if (interactive()) {
      saveEvidence <- utils::askYesNo(
        "Do you want to save all supporting evidence to a single RDS file?"
      )
    } else {
      saveEvidence <- TRUE
    }
  }

  result <- list(
    dataset = list(
      name = name,
      source = private_submission_chr(trio$dataSource),
      sourceID = private_submission_chr(trio$dataSourceID),
      file = NA_character_,
      fileName = NA_character_,
      md5 = NA_character_,
      prepared = FALSE
    ),
    evidence = list(
      source = if (length(trio$evidenceSource) > 0) trio$evidenceSource else NULL,
      sourceID = if (length(trio$evidenceSourceID) > 0) trio$evidenceSourceID else NULL,
      file = NA_character_,
      fileName = NA_character_,
      md5 = NA_character_,
      prepared = FALSE
    )
  )

  if (isTRUE(saveData)) {
    dataset_path <- file.path(outputDir, paste0(name, "_dataset.rds"))
    saveRDS(trio$data, file = dataset_path, compress = "xz")

    result$dataset$file <- dataset_path
    result$dataset$fileName <- basename(dataset_path)
    result$dataset$md5 <- unname(tools::md5sum(dataset_path))
    result$dataset$prepared <- TRUE
    result$dataset$source <- NA_character_
    result$dataset$sourceID <- NA_character_
  } else if (!isTRUE(useExistingSource)) {
    cli::cli_abort(c(
      "The dataset must either be saved for upload or already have a downloadable source.",
      "i" = "Set {.arg saveData = TRUE} or provide Trio source metadata."
    ))
  }

  if (isTRUE(saveEvidence)) {
    if (length(trio$evidence) == 0) {
      cli::cli_abort(
        "The Trio object has no supporting evidence, so no evidence file can be prepared."
      )
    }

    evidence_path <- file.path(outputDir, paste0(name, "_evidence.rds"))
    saveRDS(trio$evidence, file = evidence_path, compress = "xz")

    result$evidence$file <- evidence_path
    result$evidence$fileName <- basename(evidence_path)
    result$evidence$md5 <- unname(tools::md5sum(evidence_path))
    result$evidence$prepared <- TRUE
    result$evidence$source <- NA_character_
    result$evidence$sourceID <- NA_character_
  }

  if (isTRUE(verifyFigshare)) {
    result$figshare <- private_verify_submission_figshare(
      trio = trio,
      prepared = result,
      figshareUrl = figshareUrl,
      datasetFileName = datasetFileName,
      evidenceFileName = evidenceFileName,
      skipMd5Check = skipMd5Check
    )
  }

  result
}

#' Build DatasetTask submission rows from a Trio object
#'
#' This helper creates one `DatasetTask` row per supporting evidence name in the
#' Trio object. It does not upload anything and does not modify the existing
#' writeCTD() path.
#'
#' @param trio A `Trio` object.
#' @param datasetID Dataset identifier to link tasks to. Defaults to `NA` so the
#'   backend can fill it later.
#' @param taskStage A character vector giving the task stage for each task row.
#' @param taskType A character vector giving the task type for each task row.
#' @param taskName A character vector giving the task name for each task row.
#'
#' @return A `data.frame` matching the proposed `DatasetTask` table schema.
#'   `datasetTaskID` is left as `NA`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' buildDatasetTaskSubmission(
#'   trio,
#'   taskStage = "prediction",
#'   taskType = "classification",
#'   taskName = "class_prediction"
#' )
#' @export
buildDatasetTaskSubmission <- function(
    trio,
    datasetID = NA_character_,
    taskStage,
    taskType,
    taskName
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  n_tasks <- private_submission_row_count(taskStage, taskType, taskName)
  if (n_tasks < 1) {
    cli::cli_abort("At least one DatasetTask row must be created.")
  }

  if (length(trio$evidence) == 0) {
    cli::cli_abort(c(
      "The Trio object has no supporting evidence.",
      "i" = "Add supporting evidence before building task-linked submission tables."
    ))
  }

  taskStage <- private_recycle_submission_value(
    value = taskStage,
    n = n_tasks,
    arg = "taskStage"
  )
  taskType <- private_recycle_submission_value(
    value = taskType,
    n = n_tasks,
    arg = "taskType"
  )
  taskName <- private_recycle_submission_value(
    value = taskName,
    n = n_tasks,
    arg = "taskName"
  )
  data.frame(
    datasetTaskID = rep(NA_character_, n_tasks),
    datasetID = rep(private_submission_chr(datasetID), n_tasks),
    taskStage = private_required_submission_chr_vec(taskStage, "taskStage"),
    taskType = private_required_submission_chr_vec(taskType, "taskType"),
    taskName = private_required_submission_chr_vec(taskName, "taskName"),
    stringsAsFactors = FALSE
  )
}

#' Collect DatasetTask submission metadata interactively
#'
#' This helper gathers the task-level fields needed for the `DatasetTask`
#' table. It does not modify the `Trio` object.
#'
#' @param trio A `Trio` object.
#' @param defaults Optional named list of pre-filled task values. Supported
#'   entries are `taskStage`, `taskType`, and `taskName`. Each entry may be length 1
#'   or length `n_tasks`.
#' @param n_tasks Number of tasks to define. If `NULL`, interactive sessions
#'   prompt for this value, while non-interactive sessions infer it from the
#'   longest defaults vector.
#'
#' @return A named list ready to pass as `task_args` to
#'   `buildDatasetTaskSubmission()`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' collectTaskSubmissionInfo(
#'   trio,
#'   defaults = list(
#'     taskStage = "prediction",
#'     taskType = "classification",
#'     taskName = "class_prediction"
#'   )
#' )
#' @export
collectTaskSubmissionInfo <- function(
    trio,
    defaults = list(),
    n_tasks = NULL
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (!is.list(defaults)) {
    cli::cli_abort("{.arg defaults} must be a named list.")
  }

  if (is.null(n_tasks)) {
    default_lengths <- vapply(
      defaults[c("taskStage", "taskType", "taskName")],
      length,
      integer(1)
    )
    default_lengths <- default_lengths[default_lengths > 0]

    if (interactive()) {
      default_value <- if (length(default_lengths) == 0) "1" else as.character(max(default_lengths))
      entered <- readline(paste0("Number of tasks [", default_value, "]: "))
      entered <- if (nzchar(entered)) entered else default_value
      entered_trimmed <- trimws(entered)
      if (grepl("^[+-]?[0-9]+$", entered_trimmed)) {
        n_tasks <- as.integer(entered_trimmed)
      } else {
        n_tasks <- NA_integer_
      }
    } else if (length(default_lengths) > 0) {
      n_tasks <- max(default_lengths)
    } else {
      cli::cli_abort(
        "{.arg n_tasks} must be provided in non-interactive mode when no task defaults are supplied."
      )
    }
  }

  if (length(n_tasks) != 1 || is.na(n_tasks) || n_tasks < 1) {
    cli::cli_abort("{.arg n_tasks} must be a single positive integer.")
  }
  n_tasks <- as.integer(n_tasks)

  n_evidence <- length(trio$evidence)
  if (n_evidence == 0) {
    cli::cli_abort(
      "The Trio object has no supporting evidence, so no tasks can be collected."
    )
  }

  if (n_tasks > n_evidence) {
    cli::cli_abort(c(
      "The number of tasks cannot exceed the number of supporting evidence items in the Trio.",
      "i" = "This Trio has {.val {n_evidence}} supporting evidence item(s)."
    ))
  }

  task_stage_default <- private_collect_submission_vector(
    value = defaults$taskStage,
    n = n_tasks,
    arg = "taskStage"
  )
  task_type_default <- private_collect_submission_vector(
    value = defaults$taskType,
    n = n_tasks,
    arg = "taskType"
  )
  task_name_default <- private_collect_submission_vector(
    value = defaults$taskName,
    n = n_tasks,
    arg = "taskName"
  )
  task_stage <- character(n_tasks)
  task_type <- character(n_tasks)
  task_name <- character(n_tasks)

  for (i in seq_len(n_tasks)) {
    task_stage[[i]] <- private_collect_submission_task_stage(
      value = task_stage_default[[i]],
      title = paste0("Choose task stage for task ", i)
    )
    task_type[[i]] <- private_collect_submission_task_type(
      value = task_type_default[[i]],
      task_stage = task_stage[[i]],
      title = paste0("Choose task type for task ", i),
      prompt = paste0("Please specify task type for task ", i)
    )
    task_name[[i]] <- private_collect_submission_text(
      value = task_name_default[[i]],
      prompt = paste0("Task name for task ", i),
      required = TRUE
    )
  }

  list(
    taskStage = task_stage,
    taskType = task_type,
    taskName = task_name
  )
}

#' Build DatasetEvidence submission rows from a Trio object
#'
#' This helper creates one `DatasetEvidence` row per supporting evidence entry
#' in the Trio object. It does not upload anything and does not modify the
#' existing writeCTD() path.
#'
#' @param trio A `Trio` object.
#' @param datasetTaskID Task identifier to link evidence rows to. Defaults to
#'   generated task IDs when not supplied.
#' @param evidenceName Character vector of Trio evidence names to include.
#'   Defaults to all evidence in `trio`.
#' @param evidenceType Either \code{"columns"} or \code{"figshare"} indicating
#' where to find the evidence.
#'
#' @return A `data.frame` matching the proposed `DatasetEvidence` table schema.
#'   `evidenceID` is left as `NA`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' buildDatasetEvidenceSubmission(
#'   trio,
#'   datasetTaskID = "task_001",
#'   evidenceType = "experimental_ground_truth"
#' )
#' @export
buildDatasetEvidenceSubmission <- function(
    trio,
    datasetTaskID,
    evidenceName = names(trio$evidence),
    evidenceType = NA_character_
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  evidence_names <- private_required_submission_chr_vec(
    evidenceName,
    "evidenceName"
  )

  if (!all(evidence_names %in% names(trio$evidence))) {
    cli::cli_abort(c(
      "All {.arg evidenceName} values must exist in the Trio object.",
      "i" = "Available evidence: {.val {names(trio$evidence)}}"
    ))
  }

  if (length(evidence_names) == 0) {
    cli::cli_abort(
      "The Trio object has no supporting evidence, so no DatasetEvidence rows can be created."
    )
  }

  n_evidence <- length(evidence_names)
  datasetTaskID <- private_recycle_submission_value(
    value = datasetTaskID,
    n = n_evidence,
    arg = "datasetTaskID"
  )
  evidenceType <- private_recycle_submission_value(
    value = evidenceType,
    n = n_evidence,
    arg = "evidenceType"
  )

  data.frame(
    evidenceID = rep(NA_character_, n_evidence),
    datasetTaskID = private_submission_chr_vec(datasetTaskID),
    supportingEvidence = private_required_submission_chr_vec(
      evidence_names,
      "supportingEvidence"
    ),
    is_in_data = vapply(
      evidence_names,
      function(evidence_name) {
        private_infer_evidence_in_data(trio$evidence[[evidence_name]], trio$data)
      },
      logical(1)
    ),
    evidenceSourceID = vapply(
      evidence_names,
      function(evidence_name) {
        private_extract_evidence_source_id(trio, evidence_name)
      },
      character(1)
    ),
    evidenceType = private_submission_chr_vec(evidenceType),
    stringsAsFactors = FALSE
  )
}

#' Collect DatasetEvidence submission metadata interactively
#'
#' This helper gathers the evidence-to-task assignment and evidence type for
#' each supporting evidence item in a `Trio`.
#'
#' @param trio A `Trio` object.
#' @param task_args Named list returned by `collectTaskSubmissionInfo()`.
#' @param defaults Optional named list with entries `taskName` and
#'   `evidenceType`. Each entry may be length 1 or length equal to the number of
#'   supporting evidence items in `trio`.
#'
#' @return A named list with `datasetTaskID`, `evidenceName`,
#'   `evidenceType`, and `evidence_task_map`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' task_args <- list(
#'   taskStage = "prediction",
#'   taskType = "classification",
#'   taskName = "class_prediction"
#' )
#' collectEvidenceSubmissionInfo(
#'   trio,
#'   task_args = task_args,
#'   defaults = list(
#'     taskName = "class_prediction",
#'     evidenceType = "experimental_ground_truth"
#'   )
#' )
#' @export
collectEvidenceSubmissionInfo <- function(
    trio,
    task_args,
    defaults = list()
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (!is.list(task_args) ||
      is.null(task_args$taskName) ||
      is.null(task_args$taskType)) {
    cli::cli_abort(
      "{.arg task_args} must be a list returned by {.fn collectTaskSubmissionInfo}."
    )
  }

  if (!is.list(defaults)) {
    cli::cli_abort("{.arg defaults} must be a named list.")
  }

  evidence_names <- names(trio$evidence)
  if (length(evidence_names) == 0) {
    cli::cli_abort(
      "The Trio object has no supporting evidence, so no DatasetEvidence information can be collected."
    )
  }

  task_names <- private_required_submission_chr_vec(task_args$taskName, "taskName")
  task_temp_ids <- private_submission_task_ids(length(task_names))

  task_name_default <- private_collect_submission_vector(
    value = defaults$taskName,
    n = length(evidence_names),
    arg = "taskName"
  )
  evidence_type_default <- private_collect_submission_vector(
    value = defaults$evidenceType,
    n = length(evidence_names),
    arg = "evidenceType"
  )

  assigned_task_ids <- character(length(evidence_names))
  assigned_task_names <- character(length(evidence_names))
  evidence_type <- character(length(evidence_names))

  choices <- c(
    "experimental_ground_truth",
    "manual_annotation",
    "reference_based",
    "simulated",
    "derived_proxy",
    "other"
  )

  for (i in seq_along(evidence_names)) {
    evidence_name <- evidence_names[[i]]
    task_name <- private_collect_submission_choice(
      value = task_name_default[[i]],
      choices = task_names,
      title = paste0("Choose task for supporting evidence ", evidence_name)
    )
    assigned_task_names[[i]] <- task_name
    assigned_task_ids[[i]] <- task_temp_ids[match(task_name, task_names)]

    evidence_type[[i]] <- private_collect_submission_choice(
      value = evidence_type_default[[i]],
      choices = choices,
      title = paste0("Choose evidence type for ", evidence_name)
    )
  }

  names(assigned_task_names) <- evidence_names

  missing_tasks <- setdiff(task_names, unique(assigned_task_names))
  if (length(missing_tasks) > 0) {
    cli::cli_abort(c(
      "Each task must have at least one supporting evidence assigned.",
      "i" = "Unassigned task(s): {.val {missing_tasks}}"
    ))
  }

  list(
    datasetTaskID = assigned_task_ids,
    evidenceName = evidence_names,
    evidenceType = evidence_type,
    evidence_task_map = assigned_task_names
  )
}

#' Build Metric submission rows from a Trio object
#'
#' This helper creates one `Metric` row per metric in the Trio object. It does
#' not upload anything and does not modify the existing writeCTD() path.
#'
#' @param trio A `Trio` object.
#'
#' @return A `data.frame` matching the proposed `Metric` table schema.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' buildMetricSubmission(trio)
#' @export
buildMetricSubmission <- function(trio) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  metric_names <- names(trio$metrics)
  if (length(metric_names) == 0) {
    cli::cli_abort(
      "The Trio object has no metrics, so no Metric rows can be created."
    )
  }

  metric_type <- vapply(
    metric_names,
    private_infer_metric_type,
    character(1)
  )

  data.frame(
    metricID = rep(NA_character_, length(metric_names)),
    metricName = metric_names,
    wrapper_r = vapply(
      metric_names,
      function(metric_name) {
        private_metric_wrapper_r(metric_name, metric_type[[metric_name]])
      },
      character(1)
    ),
    metricType = rep(NA_character_, length(metric_names)),
    metricSourceType = metric_type,
    metricKey = vapply(
      metric_names,
      function(metric_name) {
        private_metric_key(
          metric_name = metric_name,
          wrapper_r = private_metric_wrapper_r(metric_name, metric_type[[metric_name]])
        )
      },
      character(1)
    ),
    wrapper_py = rep(NA_character_, length(metric_names)),
    gist_url = rep(NA_character_, length(metric_names)),
    stringsAsFactors = FALSE
  )
}

#' Prepare Trio metric metadata for submission
#'
#' This helper aligns the new submission workflow with the older `writeCTD()`
#' metric handling. Internal package metrics are recorded directly. Custom
#' metrics can optionally be uploaded to a GitHub gist and linked from the
#' resulting `Metric` table rows.
#'
#' @param trio A `Trio` object.
#' @param name Dataset name used for the gist filename. Defaults to `trio$name`.
#' @param uploadCustom Logical; if `TRUE`, custom metrics are uploaded to a
#'   GitHub gist.
#' @param githubPat Optional GitHub personal access token with gist scope.
#' @param gistPublic Logical; whether the created gist should be public.
#'
#' @return A list with entries `Metric`, `gist`, and `custom_metric_lines`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' prepareTrioSubmissionMetrics(trio)
#' @export
prepareTrioSubmissionMetrics <- function(
    trio,
    name = trio$name,
    uploadCustom = FALSE,
    githubPat = NULL,
    gistPublic = TRUE
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  metric_tbl <- buildMetricSubmission(trio)
  metric_names <- metric_tbl$metricName

  custom_metric_lines <- character(0)
  custom_metric_names <- character(0)

  for (metric_name in metric_names) {
    if (!identical(private_infer_metric_type(metric_name), "gist")) {
      next()
    }

    custom_metric_names <- c(custom_metric_names, metric_name)
    custom_metric_lines <- c(
      custom_metric_lines,
      private_submission_metric_lines(trio$metrics[[metric_name]], metric_name)
    )
  }

  gist <- NULL
  if (isTRUE(uploadCustom) && length(custom_metric_lines) > 0) {
    if (is.null(name) || !nzchar(name)) {
      cli::cli_abort(
        "{.arg name} must be provided when uploading custom metrics to a gist."
      )
    }

    gist <- private_submission_create_gist(
      content = custom_metric_lines,
      filename = paste0(name, "_metrics.R"),
      description = paste0("Metrics for Trio ", name),
      public = gistPublic,
      pat = githubPat
    )
  }

  if (length(custom_metric_names) > 0) {
    custom_rows <- metric_tbl$metricName %in% custom_metric_names
    metric_tbl$wrapper_r[custom_rows] <- metric_tbl$metricName[custom_rows]
    metric_tbl$gist_url[custom_rows] <- if (is.null(gist)) {
      NA_character_
    } else {
      gist$html_url
    }
    metric_tbl$metricKey[custom_rows] <- vapply(
      seq_along(metric_tbl$metricName[custom_rows]),
      function(i) {
        private_metric_key(
          metric_name = metric_tbl$metricName[custom_rows][[i]],
          metric_type = metric_tbl$metricSourceType[custom_rows][[i]],
          gist_url = metric_tbl$gist_url[custom_rows][[i]],
          wrapper_r = metric_tbl$wrapper_r[custom_rows][[i]]
        )
      },
      character(1)
    )
  }

  list(
    Metric = metric_tbl,
    gist = gist,
    custom_metric_lines = custom_metric_lines
  )
}

#' Collect Metric submission metadata interactively
#'
#' This helper gathers user-supplied metric classification for each metric in a
#' `Trio`. The metric names and wrappers still come from the Trio object and the
#' package helper logic.
#'
#' @param trio A `Trio` object.
#' @param defaults Optional named list with entry `metricType`. It may be length
#'   1 or length equal to the number of metrics in the Trio.
#'
#' @return A named list ready to merge into the `Metric` submission table.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' collectMetricSubmissionInfo(
#'   trio,
#'   defaults = list(metricType = "label_based")
#' )
#' @export
collectMetricSubmissionInfo <- function(
    trio,
    defaults = list()
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (!is.list(defaults)) {
    cli::cli_abort("{.arg defaults} must be a named list.")
  }

  metric_names <- names(trio$metrics)
  if (length(metric_names) == 0) {
    cli::cli_abort(
      "The Trio object has no metrics, so no metric submission information can be collected."
    )
  }

  metric_type_default <- private_collect_submission_vector(
    value = defaults$metricType,
    n = length(metric_names),
    arg = "metricType"
  )

  choices <- c(
    "label_based",
    "error_based",
    "ranking_based",
    "correlation_based",
    "distribution_based",
    "biological_based",
    "robustness_stability_based",
    "computational_efficiency_based",
    "spatial_structure",
    "topology_structure",
    "task_specific",
    "other"
  )

  metric_type <- character(length(metric_names))
  for (i in seq_along(metric_names)) {
    metric_type[[i]] <- private_collect_submission_choice(
      value = metric_type_default[[i]],
      choices = choices,
      title = paste0("Choose metric type for ", metric_names[[i]])
    )
  }

  names(metric_type) <- metric_names

  list(
    metricName = metric_names,
    metricType = metric_type
  )
}

#' Build a pre-submit Trio submission bundle
#'
#' This is the higher-level R interface for the new submission workflow. It can
#' prepare dataset/evidence files, prepare metric metadata, build the five-table
#' submission object, and return the payload/JSON for inspection before calling
#' `submitTrioSubmission()`.
#'
#' @param trio A `Trio` object.
#' @param dataset_args Named list passed to `buildDatasetSubmission()`.
#' @param task_args Named list passed to `buildDatasetTaskSubmission()`.
#' @param evidence_task_map Named character vector mapping Trio evidence names
#'   to submission task names.
#' @param prepare_files Logical; if `TRUE`, call `prepareTrioSubmissionFiles()`.
#' @param file_args Named list of additional arguments for
#'   `prepareTrioSubmissionFiles()`, excluding `trio`.
#' @param prepare_metrics Logical; if `TRUE`, call
#'   `prepareTrioSubmissionMetrics()`.
#' @param metric_args Named list of additional arguments for
#'   `prepareTrioSubmissionMetrics()`, excluding `trio`.
#' @param build_payload Logical; if `TRUE`, attach the nested payload structure.
#' @param build_json Logical; if `TRUE`, attach the JSON string.
#'
#' @return A named list containing the built `submission`, plus optional
#'   `files`, `metrics`, `payload`, and `json`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' dataset_args <- list(
#'   dataType = "omics",
#'   dataModality = "transcriptomics",
#'   technology = "RNA-seq",
#'   tissue = "blood",
#'   status = "healthy"
#' )
#' task_args <- list(
#'   taskStage = "prediction",
#'   taskType = "classification",
#'   taskName = "class_prediction"
#' )
#' bundle <- prepareTrioSubmissionBundle(
#'   trio = trio,
#'   dataset_args = dataset_args,
#'   task_args = task_args,
#'   evidence_task_map = c(class_labels = "class_prediction")
#' )
#' names(bundle)
#' @export
prepareTrioSubmissionBundle <- function(
    trio,
    dataset_args,
    task_args,
    evidence_task_map,
    prepare_files = FALSE,
    file_args = list(),
    prepare_metrics = FALSE,
    metric_args = list(),
    build_payload = TRUE,
    build_json = FALSE
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (missing(dataset_args) || !is.list(dataset_args)) {
    cli::cli_abort("{.arg dataset_args} must be a named list.")
  }

  if (missing(task_args) || !is.list(task_args)) {
    cli::cli_abort("{.arg task_args} must be a named list.")
  }

  if (missing(evidence_task_map) || is.null(evidence_task_map)) {
    cli::cli_abort(
      "{.arg evidence_task_map} must map Trio evidence names to submission task names."
    )
  }

  files <- NULL
  if (isTRUE(prepare_files)) {
    files <- do.call(
      prepareTrioSubmissionFiles,
      c(list(trio = trio), file_args)
    )
  }

  metrics <- NULL
  if (isTRUE(prepare_metrics)) {
    metrics <- do.call(
      prepareTrioSubmissionMetrics,
      c(list(trio = trio), metric_args)
    )
  }

  submission <- buildTrioSubmission(
    trio = trio,
    dataset_args = dataset_args,
    task_args = task_args,
    evidence_task_map = evidence_task_map
  )

  if (!is.null(files)) {
    submission <- private_apply_prepared_files_to_submission(submission, files)
  }

  if (!is.null(metrics)) {
    submission$Metric <- metrics$Metric
  }

  bundle <- list(
    submission = submission,
    files = files,
    metrics = metrics
  )

  if (isTRUE(build_payload)) {
    bundle$payload <- buildTrioSubmissionPayload(submission)
  }

  if (isTRUE(build_json)) {
    bundle$json <- trioSubmissionToJSON(submission)
  }

  bundle
}

#' Interactively prepare a Trio submission bundle
#'
#' This high-level helper provides a `writeCTD()`-style console workflow for
#' the new five-table submission path. It collects dataset, task, evidence, and
#' metric metadata; optionally prepares local files for upload and verifies a
#' Figshare article; optionally uploads custom metrics to a GitHub gist; and
#' returns all submission tables ready for review before calling
#' `submitTrioSubmission()`.
#'
#' @param trio A `Trio` object.
#' @param n_tasks Optional number of tasks to define. If `NULL`, interactive
#'   sessions prompt for it and non-interactive sessions require it through
#'   `task_defaults` or `n_tasks`.
#' @param dataset_defaults Optional named list passed into
#'   `collectDatasetSubmissionInfo()`.
#' @param task_defaults Optional named list passed into
#'   `collectTaskSubmissionInfo()`.
#' @param evidence_defaults Optional named list passed into
#'   `collectEvidenceSubmissionInfo()`.
#' @param metric_defaults Optional named list passed into
#'   `collectMetricSubmissionInfo()`.
#' @param prepare_files Logical; if `TRUE`, prepare dataset/evidence files or
#'   reuse an existing source.
#' @param file_args Optional named list passed into
#'   `prepareTrioSubmissionFiles()`.
#' @param upload_custom_metrics Logical; if `TRUE`, upload custom metrics to a
#'   GitHub gist.
#' @param githubPat Optional GitHub personal access token. Defaults to the
#'   current `GITHUB_PAT` environment variable.
#' @param gistPublic Logical; whether any created gist should be public.
#' @param review Logical; if `TRUE`, print a compact review summary before
#'   returning.
#' @param submit Logical; if `TRUE`, submit the built payload at the end. If
#'   `NULL`, interactive sessions ask whether to submit after the review step.
#' @param url Optional Google Apps Script endpoint URL used when
#'   `submit = TRUE`.
#' @param submittedBy Optional submitter email or identifier used when
#'   `submit = TRUE`.
#' @param build_payload Logical; if `TRUE`, attach the nested payload object.
#' @param build_json Logical; if `TRUE`, attach the JSON string.
#'
#' @return A named list containing collected arguments, optional prepared file
#'   and metric metadata, the final `submission`, and optional `payload`/`json`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' result <- writeSubmission(
#'   trio = trio,
#'   n_tasks = 1,
#'   dataset_defaults = list(
#'     dataType = "omics",
#'     dataModality = "transcriptomics",
#'     technology = "RNA-seq",
#'     tissue = "blood",
#'     status = "healthy"
#'   ),
#'   task_defaults = list(
#'     taskStage = "prediction",
#'     taskType = "classification",
#'     taskName = "class_prediction"
#'   ),
#'   evidence_defaults = list(
#'     taskName = "class_prediction",
#'     evidenceType = "experimental_ground_truth"
#'   ),
#'   metric_defaults = list(metricType = "label_based"),
#'   prepare_files = FALSE,
#'   build_json = FALSE,
#'   review = FALSE
#' )
#' names(result)
#' @export
writeSubmission <- function(
    trio,
    n_tasks = NULL,
    dataset_defaults = list(),
    task_defaults = list(),
    evidence_defaults = list(),
    metric_defaults = list(),
    prepare_files = TRUE,
    file_args = list(),
    upload_custom_metrics = FALSE,
    githubPat = Sys.getenv("GITHUB_PAT"),
    gistPublic = TRUE,
    review = TRUE,
    submit = NULL,
    url = submission_webapp_url,
    submittedBy = NULL,
    build_payload = TRUE,
    build_json = FALSE
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (!is.list(dataset_defaults) ||
      !is.list(task_defaults) ||
      !is.list(evidence_defaults) ||
      !is.list(metric_defaults) ||
      !is.list(file_args)) {
    cli::cli_abort("All defaults and {.arg file_args} inputs must be named lists.")
  }

  githubPat <- private_prepare_write_submission_pat(
    trio = trio,
    upload_custom_metrics = upload_custom_metrics,
    githubPat = githubPat
  )

  dataset_args <- collectDatasetSubmissionInfo(
    trio = trio,
    defaults = dataset_defaults
  )

  task_args <- collectTaskSubmissionInfo(
    trio = trio,
    defaults = task_defaults,
    n_tasks = n_tasks
  )

  evidence_args <- collectEvidenceSubmissionInfo(
    trio = trio,
    task_args = task_args,
    defaults = evidence_defaults
  )

  files <- NULL
  if (isTRUE(prepare_files)) {
    file_args <- private_prepare_write_submission_file_args(
      trio = trio,
      name = dataset_args$name,
      file_args = file_args
    )

    verify_now <- isTRUE(file_args$verifyFigshare)
    figshare_url <- file_args$figshareUrl
    file_args$verifyFigshare <- FALSE
    file_args$figshareUrl <- NULL

    files <- do.call(
      prepareTrioSubmissionFiles,
      c(
        list(
          trio = trio,
          name = dataset_args$name
        ),
        file_args
      )
    )

    private_inform_prepared_submission_files(files)

    if (verify_now) {
      if (interactive() && (is.null(figshare_url) || !nzchar(figshare_url))) {
        figshare_url <- private_collect_submission_text(
          prompt = "Figshare article URL",
          required = TRUE
        )
      }

      files$figshare <- private_verify_submission_figshare(
        trio = trio,
        prepared = files,
        figshareUrl = figshare_url,
        datasetFileName = file_args$datasetFileName,
        evidenceFileName = file_args$evidenceFileName,
        skipMd5Check = isTRUE(file_args$skipMd5Check)
      )
    }
  }

  metric_info <- prepareTrioSubmissionMetrics(
    trio = trio,
    name = dataset_args$name,
    uploadCustom = upload_custom_metrics,
    githubPat = githubPat,
    gistPublic = gistPublic
  )

  metric_args <- collectMetricSubmissionInfo(
    trio = trio,
    defaults = metric_defaults
  )
  metric_info$Metric$metricType <- unname(
    metric_args$metricType[
      match(metric_info$Metric$metricName, metric_args$metricName)
    ]
  )

  dataset_tbl <- do.call(
    buildDatasetSubmission,
    c(list(trio = trio), dataset_args)
  )
  task_tbl <- do.call(
    buildDatasetTaskSubmission,
    c(
      list(
        trio = trio,
        datasetID = dataset_tbl$datasetID[[1]]
      ),
      task_args
    )
  )
  evidence_tbl <- buildDatasetEvidenceSubmission(
    trio = trio,
    datasetTaskID = evidence_args$datasetTaskID,
    evidenceName = evidence_args$evidenceName,
    evidenceType = evidence_args$evidenceType
  )
  evidence_tbl$datasetTaskID[] <- NA_character_
  metric_tbl <- metric_info$Metric
  task_metric_tbl <- collectDatasetTaskMetricSubmission(
    trio = trio,
    evidence_args = evidence_args,
    task_args = task_args
  )
  task_metric_tbl$datasetTaskID[] <- NA_character_
  task_metric_tbl$metricID[] <- NA_character_

  submission <- list(
    Dataset = dataset_tbl,
    DatasetTask = task_tbl,
    DatasetEvidence = evidence_tbl,
    Metric = metric_tbl,
    DatasetTaskMetric = task_metric_tbl,
    submission_links = private_build_submission_links(
      trio = trio,
      task_args = task_args,
      evidence_args = evidence_args,
      metric_tbl = metric_tbl
    )
  )

  if (!is.null(files)) {
    submission <- private_apply_prepared_files_to_submission(submission, files)
  }

  result <- list(
    dataset_args = dataset_args,
    task_args = task_args,
    evidence_args = evidence_args,
    metric_args = metric_args,
    files = files,
    metrics = metric_info,
    submission = submission
  )

  if (isTRUE(review)) {
    private_inform_submission_review(
      submission = submission,
      files = files,
      metric_info = metric_info
    )
  }

  if (isTRUE(build_payload)) {
    result$payload <- buildTrioSubmissionPayload(submission)
  }

  if (isTRUE(build_json)) {
    result$json <- trioSubmissionToJSON(submission)
  }

  if (is.null(submit) && interactive()) {
    submit <- utils::askYesNo("Do you want to submit this bundle now?")
  }

  if (isTRUE(submit)) {
    if (is.null(url) || !nzchar(as.character(url))) {
      if (!interactive()) {
        cli::cli_abort(
          "{.arg url} must be provided when {.arg submit = TRUE} in non-interactive mode."
        )
      }
      url <- private_collect_submission_text(
        prompt = "Google Apps Script URL",
        required = TRUE
      )
    }

    if (is.null(submittedBy) || !nzchar(as.character(submittedBy))) {
      if (!interactive()) {
        cli::cli_abort(
          "{.arg submittedBy} must be provided when {.arg submit = TRUE} in non-interactive mode."
        )
      }
      submittedBy <- private_collect_submission_text(
        prompt = "Submitted by",
        required = TRUE
      )
    }

    result$submit_response <- submitTrioSubmission(
      submission = submission,
      url = url,
      submittedBy = submittedBy,
      submittedType = "Trio"
    )

    if (isTRUE(result$submit_response$ok)) {
      cli::cli_inform("Submission completed successfully.")
    } else {
      cli::cli_inform("Submission request finished, but the response was not marked as successful.")
    }
  }

  result
}

#' Build DatasetTaskMetric submission rows from a Trio object
#'
#' This helper creates one `DatasetTaskMetric` row for each task-metric pairing.
#' It does not upload anything and does not modify the existing writeCTD() path.
#'
#' @param trio A `Trio` object.
#' @param datasetTaskID Task identifier(s) to link metrics to. Defaults to `NA`
#'   generated task IDs when not supplied.
#' @param taskMetrics A named list mapping each `datasetTaskID` to its metric
#'   IDs. If omitted, metrics are inferred from the evidence assigned to each
#'   task via `evidenceTaskID`.
#' @param evidenceTaskID Character vector mapping each Trio evidence entry to a
#'   `datasetTaskID`. Used when `taskMetrics` is not supplied.
#' @param evidenceName Character vector of Trio evidence names corresponding to
#'   `evidenceTaskID`. Defaults to all evidence in `trio`.
#'
#' @return A `data.frame` matching the proposed `DatasetTaskMetric` table
#'   schema. `datasetTaskMetricID` and `metricID` are left as `NA`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' buildDatasetTaskMetricSubmission(
#'   trio,
#'   datasetTaskID = "task_001",
#'   evidenceTaskID = "task_001"
#' )
#' @export
buildDatasetTaskMetricSubmission <- function(
    trio,
    datasetTaskID,
    taskMetrics = NULL,
    evidenceTaskID = NULL,
    evidenceName = names(trio$evidence)
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  datasetTaskID <- unique(private_required_submission_chr_vec(
    datasetTaskID,
    "datasetTaskID"
  ))

  if (length(datasetTaskID) == 0) {
    cli::cli_abort(
      "At least one {.arg datasetTaskID} value must be supplied."
    )
  }

  if (is.null(taskMetrics)) {
    evidence_names <- private_required_submission_chr_vec(
      evidenceName,
      "evidenceName"
    )
    if (!all(evidence_names %in% names(trio$evidence))) {
      cli::cli_abort(c(
        "All {.arg evidenceName} values must exist in the Trio object.",
        "i" = "Available evidence: {.val {names(trio$evidence)}}"
      ))
    }

    evidenceTaskID <- private_recycle_submission_value(
      value = evidenceTaskID,
      n = length(evidence_names),
      arg = "evidenceTaskID"
    )

    taskMetrics <- lapply(datasetTaskID, function(one_task_id) {
      task_evidence <- evidence_names[evidenceTaskID == one_task_id]
      unique(unlist(lapply(task_evidence, trio$getMetrics), use.names = FALSE))
    })
    names(taskMetrics) <- datasetTaskID
  } else {
    if (!is.list(taskMetrics) || is.null(names(taskMetrics))) {
      cli::cli_abort(
        "{.arg taskMetrics} must be a named list keyed by datasetTaskID."
      )
    }
  }

  rows <- lapply(datasetTaskID, function(one_task_id) {
    metric_ids <- taskMetrics[[one_task_id]]

    if (is.null(metric_ids) || length(metric_ids) == 0) {
      return(NULL)
    }

    metric_ids <- unique(private_required_submission_chr_vec(
      metric_ids,
      "metricID"
    ))

    data.frame(
      datasetTaskMetricID = rep(NA_character_, length(metric_ids)),
      datasetTaskID = rep(one_task_id, length(metric_ids)),
      metricID = metric_ids,
      stringsAsFactors = FALSE
    )
  })

  rows <- Filter(Negate(is.null), rows)
  if (length(rows) == 0) {
    return(data.frame(
      datasetTaskMetricID = character(0),
      datasetTaskID = character(0),
      metricID = character(0),
      stringsAsFactors = FALSE
    ))
  }

  do.call(rbind, rows)
}

#' Collect DatasetTaskMetric submission rows from Trio assignments
#'
#' This helper builds the `DatasetTaskMetric` linking table automatically from
#' the evidence-to-task assignments and the metric links already stored inside
#' the `Trio` object.
#'
#' @param trio A `Trio` object.
#' @param evidence_args Named list returned by
#'   `collectEvidenceSubmissionInfo()`.
#' @param task_args Named list returned by `collectTaskSubmissionInfo()`.
#'
#' @return A `data.frame` matching the `DatasetTaskMetric` schema.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' collectDatasetTaskMetricSubmission(
#'   trio,
#'   evidence_args = list(
#'     datasetTaskID = "task_001",
#'     evidenceName = "class_labels"
#'   ),
#'   task_args = list(
#'     taskStage = "prediction",
#'     taskType = "classification",
#'     taskName = "class_prediction"
#'   )
#' )
#' @export
collectDatasetTaskMetricSubmission <- function(
    trio,
    evidence_args,
    task_args
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (!is.list(evidence_args) ||
      is.null(evidence_args$datasetTaskID) ||
      is.null(evidence_args$evidenceName)) {
    cli::cli_abort(
      "{.arg evidence_args} must be a list returned by {.fn collectEvidenceSubmissionInfo}."
    )
  }

  if (!is.list(task_args) ||
      is.null(task_args$taskName)) {
    cli::cli_abort(
      "{.arg task_args} must be a list returned by {.fn collectTaskSubmissionInfo}."
    )
  }

  buildDatasetTaskMetricSubmission(
    trio = trio,
    datasetTaskID = private_submission_task_ids(length(task_args$taskName)),
    evidenceTaskID = evidence_args$datasetTaskID,
    evidenceName = evidence_args$evidenceName
  )
}

#' Build a combined Trio submission object
#'
#' This helper assembles the five Trio-focused submission tables into a single
#' list so it can be inspected locally before any upload step is added.
#'
#' @param trio A `Trio` object.
#' @param dataset_args Named list of arguments passed to
#'   `buildDatasetSubmission()`, excluding `trio`.
#' @param task_args Named list of arguments passed to
#'   `buildDatasetTaskSubmission()`, excluding `trio`.
#' @param evidence_task_map Character vector mapping Trio evidence names to the
#'   corresponding task names in the submission. Names must be evidence names
#'   from `trio$evidence`, values must be task names supplied in `task_args`.
#'
#' @return A named list containing `Dataset`, `DatasetTask`,
#'   `DatasetEvidence`, `Metric`, `DatasetTaskMetric`, and
#'   `submission_links`.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' dataset_args <- list(
#'   dataType = "omics",
#'   dataModality = "transcriptomics",
#'   technology = "RNA-seq",
#'   tissue = "blood",
#'   status = "healthy"
#' )
#' task_args <- list(
#'   taskStage = "prediction",
#'   taskType = "classification",
#'   taskName = "class_prediction"
#' )
#' submission <- buildTrioSubmission(
#'   trio = trio,
#'   dataset_args = dataset_args,
#'   task_args = task_args,
#'   evidence_task_map = c(class_labels = "class_prediction")
#' )
#' names(submission)
#' @export
buildTrioSubmission <- function(
    trio,
    dataset_args,
    task_args,
    evidence_task_map
) {
  if (!inherits(trio, "Trio")) {
    cli::cli_abort("{.arg trio} must be a {.cls Trio} object.")
  }

  if (missing(dataset_args) || !is.list(dataset_args)) {
    cli::cli_abort("{.arg dataset_args} must be a named list.")
  }

  if (missing(task_args) || !is.list(task_args)) {
    cli::cli_abort("{.arg task_args} must be a named list.")
  }

  if (missing(evidence_task_map) || is.null(evidence_task_map)) {
    cli::cli_abort(
      "{.arg evidence_task_map} must map Trio evidence names to submission task names."
    )
  }

  if (is.null(names(evidence_task_map))) {
    cli::cli_abort(
      "{.arg evidence_task_map} must be a named character vector."
    )
  }

  evidence_task_map <- private_required_submission_chr_vec(
    evidence_task_map,
    "evidence_task_map"
  )

  if (!all(names(evidence_task_map) %in% names(trio$evidence))) {
    cli::cli_abort(c(
      "Names of {.arg evidence_task_map} must be Trio evidence names.",
      "i" = "Available evidence: {.val {names(trio$evidence)}}"
    ))
  }

  dataset_tbl <- do.call(
    buildDatasetSubmission,
    c(list(trio = trio), dataset_args)
  )

  task_tbl <- do.call(
    buildDatasetTaskSubmission,
    c(
      list(
        trio = trio,
        datasetID = dataset_tbl$datasetID[[1]]
      ),
      task_args
    )
  )

  task_temp_ids <- private_submission_task_ids(nrow(task_tbl))
  task_lookup <- stats::setNames(task_temp_ids, task_tbl$taskName)

  if (!all(unname(evidence_task_map) %in% task_tbl$taskName)) {
    cli::cli_abort(c(
      "All values of {.arg evidence_task_map} must match a submitted task name.",
      "i" = "Available task names: {.val {task_tbl$taskName}}"
    ))
  }

  ordered_evidence_names <- names(evidence_task_map)
  evidence_task_ids <- unname(task_lookup[evidence_task_map])

  evidence_tbl <- buildDatasetEvidenceSubmission(
    trio,
    datasetTaskID = evidence_task_ids,
    evidenceName = ordered_evidence_names
  )
  evidence_tbl$datasetTaskID <- NA_character_
  metric_tbl <- buildMetricSubmission(trio)
  metric_temp_ids <- private_submission_metric_ids(metric_tbl$metricName)
  task_metric_tbl <- buildDatasetTaskMetricSubmission(
    trio,
    datasetTaskID = task_temp_ids,
    evidenceTaskID = evidence_task_ids,
    evidenceName = ordered_evidence_names
  )
  task_metric_tbl$datasetTaskID <- NA_character_
  task_metric_tbl$metricID <- NA_character_

  list(
    Dataset = dataset_tbl,
    DatasetTask = task_tbl,
    DatasetEvidence = evidence_tbl,
    Metric = metric_tbl,
    DatasetTaskMetric = task_metric_tbl,
    submission_links = list(
      dataset_temp_id = private_submission_dataset_id(),
      task = data.frame(
        task_temp_id = task_temp_ids,
        taskName = task_tbl$taskName,
        stringsAsFactors = FALSE
      ),
      evidence = data.frame(
        evidenceName = ordered_evidence_names,
        task_temp_id = evidence_task_ids,
        stringsAsFactors = FALSE
      ),
      metric = private_build_metric_links(metric_tbl, metric_temp_ids),
      task_metric = private_build_task_metric_links(
        trio = trio,
        evidence_names = ordered_evidence_names,
        evidence_task_ids = evidence_task_ids,
        metric_temp_ids = metric_temp_ids,
        metric_tbl = metric_tbl
      )
    )
  )
}

#' Convert a combined Trio submission to payload structure
#'
#' This helper converts the output of `buildTrioSubmission()` into the nested
#' list structure used by the JSON payload in the prototype submission script.
#'
#' @param submission A submission object returned by `buildTrioSubmission()`.
#'
#' @return A named list with a top-level `payload` entry ready for
#'   `jsonlite::toJSON(..., auto_unbox = TRUE)`.
#' @importFrom jsonlite toJSON
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' submission <- buildTrioSubmission(
#'   trio = trio,
#'   dataset_args = list(
#'     dataType = "omics",
#'     dataModality = "transcriptomics",
#'     technology = "RNA-seq",
#'     tissue = "blood",
#'     status = "healthy"
#'   ),
#'   task_args = list(
#'     taskStage = "prediction",
#'     taskType = "classification",
#'     taskName = "class_prediction"
#'   ),
#'   evidence_task_map = c(class_labels = "class_prediction")
#' )
#' payload <- buildTrioSubmissionPayload(submission)
#' names(payload)
#' @export
buildTrioSubmissionPayload <- function(submission) {
  required_names <- c(
    "Dataset",
    "DatasetTask",
    "DatasetEvidence",
    "Metric",
    "DatasetTaskMetric"
  )

  if (!is.list(submission)) {
    cli::cli_abort("{.arg submission} must be a submission list.")
  }

  missing_names <- setdiff(required_names, names(submission))
  if (length(missing_names) > 0) {
    cli::cli_abort(c(
      "The submission object is missing required tables.",
      "i" = "Missing: {.val {missing_names}}"
    ))
  }

  payload_tables <- list(
    Dataset = private_submission_df_to_records(submission$Dataset),
    DatasetTask = private_submission_df_to_records(submission$DatasetTask),
    DatasetEvidence = private_submission_df_to_records(submission$DatasetEvidence),
    Metric = private_submission_df_to_records(submission$Metric),
    DatasetTaskMetric = private_submission_df_to_records(submission$DatasetTaskMetric)
  )

  payload <- list(payload = payload_tables)

  if (!is.null(submission$submission_links)) {
    payload$submission_links <- list(
      dataset_temp_id = submission$submission_links$dataset_temp_id,
      task = private_submission_df_to_records(submission$submission_links$task),
      evidence = private_submission_df_to_records(submission$submission_links$evidence),
      metric = private_submission_df_to_records(submission$submission_links$metric),
      task_metric = private_submission_df_to_records(submission$submission_links$task_metric)
    )
  }

  payload
}

#' Convert a combined Trio submission to JSON
#'
#' @param submission A submission object returned by `buildTrioSubmission()`.
#' @param pretty Whether to pretty-print the JSON. Defaults to `TRUE`.
#'
#' @return A JSON string.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' submission <- buildTrioSubmission(
#'   trio = trio,
#'   dataset_args = list(
#'     dataType = "omics",
#'     dataModality = "transcriptomics",
#'     technology = "RNA-seq",
#'     tissue = "blood",
#'     status = "healthy"
#'   ),
#'   task_args = list(
#'     taskStage = "prediction",
#'     taskType = "classification",
#'     taskName = "class_prediction"
#'   ),
#'   evidence_task_map = c(class_labels = "class_prediction")
#' )
#' json <- trioSubmissionToJSON(submission)
#' substr(json, 1, 20)
#' @export
trioSubmissionToJSON <- function(
    submission,
    pretty = TRUE
) {
  payload <- buildTrioSubmissionPayload(submission = submission)

  jsonlite::toJSON(
    payload,
    auto_unbox = TRUE,
    pretty = pretty,
    null = "null",
    na = "null"
  )
}

#' Submit a Trio submission payload to Google Apps Script
#'
#' This helper posts the Trio submission payload to a Google Apps Script
#' endpoint using the same redirect-tolerant approach as the prototype script.
#'
#' @param submission A submission object returned by `buildTrioSubmission()`.
#' @param url Google Apps Script endpoint URL.
#' @param submittedBy Submitter email or identifier.
#' @param submittedType Submission type label. Defaults to `"Trio"`.
#'
#' @return A list containing request status information and response text.
#' @examples
#' data <- data.frame(feature = c(1, 2, 3), row.names = paste0("sample", 1:3))
#' labels <- factor(c("A", "B", "A"))
#' names(labels) <- rownames(data)
#' trio <- Trio$new(
#'   data = data,
#'   evidence = list(class_labels = list(
#'     evidence = labels,
#'     metrics = "macroF1Metric"
#'   )),
#'   metrics = list(macroF1Metric = macroF1Metric),
#'   name = "example_dataset",
#'   description = "A small example dataset."
#' )
#' submission <- buildTrioSubmission(
#'   trio = trio,
#'   dataset_args = list(
#'     dataType = "omics",
#'     dataModality = "transcriptomics",
#'     technology = "RNA-seq",
#'     tissue = "blood",
#'     status = "healthy"
#'   ),
#'   task_args = list(
#'     taskStage = "prediction",
#'     taskType = "classification",
#'     taskName = "class_prediction"
#'   ),
#'   evidence_task_map = c(class_labels = "class_prediction")
#' )
#'
#' if (interactive() && curl::has_internet()) {
#'   response <- submitTrioSubmission(
#'     submission,
#'     url = "https://script.google.com/macros/s/example/exec",
#'     submittedBy = "researcher@example.org"
#'   )
#'   names(response)
#' }
#' @export
submitTrioSubmission <- function(
    submission,
    url,
    submittedBy,
    submittedType = "Trio"
) {
  if (!curl::has_internet()) {
    cli::cli_abort("No internet connection available.")
  }

  if (missing(url) || is.null(url) || !is.character(url) ||
      length(url) != 1 || is.na(url) || !nzchar(url)) {
    cli::cli_abort(
      "{.arg url} must be a single non-empty character string."
    )
  }

  if (missing(submittedBy) || is.null(submittedBy) ||
      !is.character(submittedBy) || length(submittedBy) != 1 ||
      is.na(submittedBy) || !nzchar(submittedBy)) {
    cli::cli_abort(
      "{.arg submittedBy} must be a single non-empty character string."
    )
  }

  if (missing(submittedType) || is.null(submittedType) ||
      !is.character(submittedType) || length(submittedType) != 1 ||
      is.na(submittedType) || !nzchar(submittedType)) {
    cli::cli_abort(
      "{.arg submittedType} must be a single non-empty character string."
    )
  }

  payload <- buildTrioSubmissionPayload(submission = submission)

  body <- list(
    submittedBy = submittedBy,
    submittedType = submittedType,
    payload = payload
  )

  resp1 <- httr2::request(url) |>
    httr2::req_method("POST") |>
    httr2::req_headers(`Content-Type` = "application/json") |>
    httr2::req_body_json(body, auto_unbox = TRUE) |>
    httr2::req_options(followlocation = FALSE) |>
    httr2::req_error(is_error = function(resp) FALSE) |>
    httr2::req_perform()

  status1 <- httr2::resp_status(resp1)
  headers1 <- httr2::resp_headers(resp1)

  if (status1 %in% c(301, 302, 303, 307, 308) &&
      !is.null(headers1[["location"]])) {
    resp2 <- httr2::request(headers1[["location"]]) |>
      httr2::req_method("GET") |>
      httr2::req_error(is_error = function(resp) FALSE) |>
      httr2::req_perform()

    return(list(
      ok = httr2::resp_status(resp2) == 200,
      post_status = status1,
      final_status = httr2::resp_status(resp2),
      final_body = httr2::resp_body_string(resp2)
    ))
  }

  list(
    ok = status1 == 200,
    post_status = status1,
    final_status = status1,
    final_body = httr2::resp_body_string(resp1)
  )
}

private_validate_submission_choice <- function(value, arg, choices) {
  if (missing(value) || is.null(value) || length(value) != 1 || !nzchar(value)) {
    cli::cli_abort(
      "The {.arg {arg}} argument must be a single non-empty string."
    )
  }

  if (!value %in% choices) {
    cli::cli_abort(c(
      "Invalid value for {.arg {arg}}.",
      "i" = "Choose one of: {.val {choices}}"
    ))
  }
}

private_get_submission_num_samples <- function(data) {
  if (is.null(data)) {
    return(NA_integer_)
  }

  if (inherits(data, "SingleCellExperiment")) {
    return(as.integer(ncol(data)))
  }

  if (isTabular(data) && !is.null(nrow(data))) {
    return(as.integer(nrow(data)))
  }

  dims <- dim(data)
  if (!is.null(dims) && length(dims) >= 1) {
    return(as.integer(dims[[1]]))
  }

  NA_integer_
}

private_submission_chr <- function(x) {
  if (is.null(x) || length(x) == 0 || is.na(x) || !nzchar(as.character(x))) {
    return(NA_character_)
  }

  as.character(x)
}

private_submission_chr_vec <- function(x) {
  x_chr <- as.character(x)
  x_chr[is.na(x_chr) | !nzchar(x_chr)] <- NA_character_
  x_chr
}

private_recycle_submission_value <- function(value, n, arg) {
  if (missing(value) || is.null(value) || length(value) == 0) {
    cli::cli_abort(
      "The {.arg {arg}} argument must be provided."
    )
  }

  if (length(value) == 1) {
    return(rep(value, n))
  }

  if (length(value) != n) {
    cli::cli_abort(c(
      "Invalid length for {.arg {arg}}.",
      "i" = "Provide either one value or exactly {.val {n}} values."
    ))
  }

  value
}

private_submission_row_count <- function(...) {
  lengths <- vapply(list(...), length, integer(1))
  lengths <- lengths[lengths > 0]

  if (length(lengths) == 0) {
    cli::cli_abort("At least one submission field must be provided.")
  }

  max(lengths)
}

private_required_submission_chr_vec <- function(x, arg) {
  x_chr <- as.character(x)
  names(x_chr) <- names(x)

  if (any(is.na(x_chr) | !nzchar(x_chr))) {
    cli::cli_abort(
      "All values in {.arg {arg}} must be non-empty strings."
    )
  }

  x_chr
}

private_infer_evidence_in_data <- function(one_evidence, data) {
  evidence_data <- one_evidence$evidence

  if (is.function(evidence_data)) {
    return(TRUE)
  }

  if (isTabular(evidence_data)) {
    return(identical(rownames(evidence_data), rownames(data)))
  }

  if (!is.null(names(evidence_data)) && !is.null(rownames(data))) {
    return(identical(names(evidence_data), rownames(data)))
  }

  FALSE
}

private_extract_evidence_source_id <- function(trio, evidence_name) {
  source_ids <- trio$evidenceSourceID

  if (is.null(source_ids) || length(source_ids) == 0) {
    return(NA_character_)
  }

  if (!is.null(names(source_ids)) && evidence_name %in% names(source_ids)) {
    return(private_submission_chr(source_ids[[evidence_name]]))
  }

  if (length(source_ids) == 1) {
    return(private_submission_chr(source_ids[[1]]))
  }

  NA_character_
}

private_infer_metric_type <- function(metric_name) {
  if (!is.na(private_find_internal_metric_wrapper(metric_name))) {
    return("internal")
  }

  "gist"
}

private_metric_wrapper_r <- function(metric_name, metric_type) {
  if (identical(metric_type, "internal")) {
    return(private_find_internal_metric_wrapper(metric_name))
  }

  NA_character_
}

private_metric_key <- function(metric_name, metric_type = NULL, gist_url = NULL, wrapper_r = NULL) {
  if (is.null(metric_type) || is.na(metric_type) || !nzchar(metric_type)) {
    metric_type <- private_infer_metric_type(metric_name)
  }

  if (is.null(wrapper_r) || is.na(wrapper_r) || !nzchar(wrapper_r)) {
    wrapper_r <- private_metric_wrapper_r(metric_name, metric_type)
  }

  if (identical(metric_type, "internal")) {
    if (is.null(wrapper_r) || is.na(wrapper_r) || !nzchar(wrapper_r)) {
      return(NA_character_)
    }
    return(wrapper_r)
  }

  if (identical(metric_type, "gist")) {
    if (is.null(gist_url) || is.na(gist_url) || !nzchar(gist_url)) {
      return(NA_character_)
    }
    gist_id <- private_extract_gist_id(gist_url)
    if (is.na(gist_id) || !nzchar(gist_id)) {
      return(NA_character_)
    }
    if (is.null(wrapper_r) || is.na(wrapper_r) || !nzchar(wrapper_r)) {
      return(NA_character_)
    }
    return(paste0(gist_id, "|", wrapper_r))
  }

  NA_character_
}

private_extract_gist_id <- function(gist_url) {
  if (is.null(gist_url) || is.na(gist_url) || !nzchar(gist_url)) {
    return(NA_character_)
  }

  parts <- strsplit(gist_url, "/")[[1]]
  parts <- parts[nzchar(parts)]
  if (length(parts) == 0) {
    return(NA_character_)
  }

  tail(parts, 1)
}

private_submission_df_to_records <- function(df) {
  if (!is.data.frame(df)) {
    cli::cli_abort("Each submission table must be a data.frame.")
  }

  if (nrow(df) == 0) {
    return(list())
  }

  lapply(seq_len(nrow(df)), function(i) {
    as.list(df[i, , drop = FALSE])
  })
}

private_submission_dataset_id <- function() {
  "SUBMISSION_DATASET_1"
}

private_submission_task_ids <- function(n_tasks) {
  paste0("SUBMISSION_TASK_", seq_len(n_tasks))
}

private_submission_evidence_ids <- function(evidence_names) {
  paste0("SUBMISSION_EVIDENCE_", seq_along(evidence_names))
}

private_submission_metric_ids <- function(metric_names) {
  paste0("SUBMISSION_METRIC_", seq_along(metric_names))
}

private_submission_task_metric_ids <- function(task_id, metric_ids) {
  paste0(
    "SUBMISSION_TASK_METRIC_",
    make.names(task_id),
    "_",
    seq_along(metric_ids)
  )
}

private_verify_submission_figshare <- function(
    trio,
    prepared,
    figshareUrl,
    datasetFileName = NULL,
    evidenceFileName = NULL,
    skipMd5Check = FALSE
) {
  if (missing(figshareUrl) || is.null(figshareUrl) || !nzchar(figshareUrl)) {
    cli::cli_abort("{.arg figshareUrl} must be provided when verifying Figshare upload.")
  }

  if (!grepl("figshare", figshareUrl, ignore.case = TRUE)) {
    cli::cli_abort("{.arg figshareUrl} must be a Figshare URL.")
  }

  article_id <- stringr::str_extract(figshareUrl, "(?<=/)[0-9]+")
  if (is.na(article_id) || !nzchar(article_id)) {
    cli::cli_abort("Could not extract a Figshare article ID from {.arg figshareUrl}.")
  }

  file_df <- figshareListFiles(article_id)
  if (nrow(file_df) == 0) {
    cli::cli_abort("No files were found in the Figshare article.")
  }

  dataset_match <- NULL
  if (isTRUE(prepared$dataset$prepared)) {
    dataset_match <- private_match_submission_figshare_file(
      available = file_df,
      preferred = datasetFileName,
      default_name = prepared$dataset$fileName,
      suffix = "_dataset.rds"
    )
  }

  evidence_match <- NULL
  if (isTRUE(prepared$evidence$prepared)) {
    evidence_match <- private_match_submission_figshare_file(
      available = file_df,
      preferred = evidenceFileName,
      default_name = prepared$evidence$fileName,
      suffix = "_evidence.rds"
    )
  }

  dataset_md5_ok <- NA
  if (!is.null(dataset_match)) {
    dataset_md5_ok <- !is.na(prepared$dataset$md5) &&
      identical(unname(file_df$computed_md5[dataset_match$row]), prepared$dataset$md5)
  }

  if (isTRUE(prepared$dataset$prepared) && !dataset_md5_ok && !skipMd5Check) {
    cli::cli_abort("Uploaded dataset file MD5 does not match the prepared dataset file.")
  }

  evidence_md5_ok <- NA
  if (!is.null(evidence_match)) {
    evidence_md5_ok <- !is.na(prepared$evidence$md5) &&
      identical(unname(file_df$computed_md5[evidence_match$row]), prepared$evidence$md5)
    if (!evidence_md5_ok && !skipMd5Check) {
      cli::cli_abort("Uploaded evidence file MD5 does not match the prepared evidence file.")
    }
  }

  list(
    article_id = article_id,
    dataset = if (is.null(dataset_match)) {
      NULL
    } else {
      list(
        fileName = dataset_match$file_name,
        fileID = as.character(file_df$id[dataset_match$row]),
        source = "figshare",
        sourceID = paste0(article_id, "/", file_df$id[dataset_match$row]),
        md5_ok = dataset_md5_ok
      )
    },
    evidence = if (is.null(evidence_match)) {
      NULL
    } else {
      list(
        fileName = evidence_match$file_name,
        fileID = as.character(file_df$id[evidence_match$row]),
        source = "figshare",
        sourceID = paste0(article_id, "/", file_df$id[evidence_match$row]),
        md5_ok = evidence_md5_ok
      )
    }
  )
}

private_match_submission_figshare_file <- function(
    available,
    preferred = NULL,
    default_name = NULL,
    suffix
) {
  file_names <- available$name

  candidates <- c(preferred, default_name)
  candidates <- candidates[!is.na(candidates) & nzchar(candidates)]

  for (candidate in candidates) {
    idx <- which(file_names == candidate)
    if (length(idx) > 0) {
      return(list(row = idx[[1]], file_name = file_names[[idx[[1]]]]))
    }
  }

  suffix_idx <- which(endsWith(tolower(file_names), tolower(suffix)))
  if (length(suffix_idx) > 0) {
    idx <- suffix_idx[[1]]
    return(list(row = idx, file_name = file_names[[idx]]))
  }

  cli::cli_abort(c(
    "Could not find the expected uploaded file in the Figshare article.",
    "i" = "Available files: {.val {file_names}}"
  ))
}

private_submission_metric_lines <- function(metric_fn, metric_name) {
  metric_env <- environment(metric_fn)

  if (!is.null(metric_env) &&
      exists("metric", envir = metric_env, inherits = FALSE)) {
    metric <- get("metric", envir = metric_env, inherits = FALSE)
    args <- if (exists("args", envir = metric_env, inherits = FALSE)) {
      get("args", envir = metric_env, inherits = FALSE)
    } else {
      NULL
    }
  } else {
    metric <- metric_fn
    args <- NULL
  }

  metric_deparsed <- deparse(metric)
  metric_deparsed[1] <- paste0(metric_name, " <- ", metric_deparsed[1])
  args_deparsed <- paste0(metric_name, "Args <- ", deparse(args))

  c(metric_deparsed, args_deparsed)
}

private_submission_create_gist <- function(
    content,
    filename,
    description,
    public = TRUE,
    pat = NULL
) {
  if (exists("createGist", mode = "function")) {
    return(createGist(
      content = content,
      filename = filename,
      description = description,
      public = public,
      pat = pat
    ))
  }

  if (exists("creatGist", mode = "function")) {
    return(creatGist(
      content = content,
      filename = filename,
      description = description,
      public = public,
      pat = pat
    ))
  }

  cli::cli_abort("No gist creation helper is available in the current session.")
}

private_prepare_write_submission_file_args <- function(trio, name, file_args) {
  if (!interactive()) {
    return(file_args)
  }

  if (is.null(file_args$useExistingSource)) {
    existing_source_available <- !is.null(trio$dataSource) &&
      nzchar(as.character(trio$dataSource)) &&
      !is.null(trio$dataSourceID) &&
      nzchar(as.character(trio$dataSourceID))

    if (existing_source_available) {
      use_existing <- utils::askYesNo(
        "Do you want to keep the existing Trio download source instead of preparing a new dataset file?"
      )
      if (is.na(use_existing)) {
        cli::cli_abort("Submission file preparation cancelled.")
      }
      if (isTRUE(use_existing)) {
        file_args$useExistingSource <- TRUE
        file_args$saveData <- FALSE
      } else {
        file_args$useExistingSource <- FALSE
      }
    } else {
      file_args$useExistingSource <- FALSE
    }
  }

  if (is.null(file_args$saveData)) {
    file_args$saveData <- !isTRUE(file_args$useExistingSource)
  }
  if (is.null(file_args$saveEvidence)) {
    file_args$saveEvidence <- TRUE
  }

  if (isTRUE(file_args$useExistingSource) && !isTRUE(file_args$saveData)) {
    cli::cli_inform(c(
      "Using existing Trio dataset source.",
      "i" = paste0(
        "Dataset source: ",
        private_submission_chr(trio$dataSource),
        " / ",
        private_submission_chr(trio$dataSourceID)
      ),
      "i" = "Only supporting evidence will be prepared if needed."
    ))
  }

  if (is.null(file_args$outputDir) &&
      (isTRUE(file_args$saveData) || isTRUE(file_args$saveEvidence))) {
    use_current_dir <- utils::askYesNo(
      "Do you want to save the submission RDS file(s) in the current dir?"
    )

    if (is.na(use_current_dir)) {
      cli::cli_abort("Submission file preparation cancelled.")
    }

    if (isTRUE(use_current_dir)) {
      file_args$outputDir <- getwd()
    } else {
      chosen_dir <- private_collect_submission_text(
        prompt = "Please specify the download dir",
        required = TRUE
      )
      if (!dir.exists(chosen_dir)) {
        cli::cli_abort("{.arg chosen_dir} must be an existing directory.")
      }
      file_args$outputDir <- chosen_dir
    }
  }

  if ((isTRUE(file_args$saveData) || isTRUE(file_args$saveEvidence)) &&
      is.null(file_args$verifyFigshare)) {
    verify_figshare <- utils::askYesNo(
      "After uploading to Figshare, do you want to verify the article link now?"
    )
    file_args$verifyFigshare <- isTRUE(verify_figshare)
  }

  file_args
}

private_prepare_write_submission_pat <- function(
    trio,
    upload_custom_metrics,
    githubPat
) {
  if (!isTRUE(upload_custom_metrics)) {
    return(githubPat)
  }

  metric_names <- names(trio$metrics)
  has_custom <- any(vapply(metric_names, private_infer_metric_type, character(1)) == "gist")
  if (!has_custom) {
    return(githubPat)
  }

  if (!is.null(githubPat) && nzchar(githubPat)) {
    if (interactive()) {
      cli::cli_inform("The GITHUB_PAT environment variable is set. Let's get started it!")
    }
    return(githubPat)
  }

  if (!interactive()) {
    return(githubPat)
  }

  cli::cli_inform(c(
    "The GITHUB_PAT environment variable is not set.",
    "A GitHub personal access token with gist access is needed to upload custom metrics."
  ))

  use_pat <- utils::askYesNo(
    "Do you want to enter a token for this submission?"
  )
  if (!isTRUE(use_pat)) {
    return(githubPat)
  }

  pat <- private_collect_submission_text(
    prompt = "Enter your GitHub personal access token",
    required = TRUE
  )
  pat
}

private_build_submission_links <- function(trio, task_args, evidence_args, metric_tbl) {
  task_temp_ids <- private_submission_task_ids(length(task_args$taskName))
  metric_temp_ids <- private_submission_metric_ids(metric_tbl$metricName)

  list(
    dataset_temp_id = private_submission_dataset_id(),
    task = data.frame(
      task_temp_id = task_temp_ids,
      taskName = task_args$taskName,
      stringsAsFactors = FALSE
    ),
    evidence = data.frame(
      evidenceName = evidence_args$evidenceName,
      task_temp_id = evidence_args$datasetTaskID,
      stringsAsFactors = FALSE
    ),
    metric = private_build_metric_links(metric_tbl, metric_temp_ids),
    task_metric = private_build_task_metric_links(
      trio = trio,
      evidence_names = evidence_args$evidenceName,
      evidence_task_ids = evidence_args$datasetTaskID,
      metric_temp_ids = metric_temp_ids,
      metric_tbl = metric_tbl
    )
  )
}

private_build_metric_links <- function(metric_tbl, metric_temp_ids) {
  data.frame(
    metric_temp_id = metric_temp_ids,
    metricName = metric_tbl$metricName,
    metricSourceType = metric_tbl$metricSourceType,
    metricKey = metric_tbl$metricKey,
    gist_url = metric_tbl$gist_url,
    stringsAsFactors = FALSE
  )
}

private_build_task_metric_links <- function(
    trio,
    evidence_names,
    evidence_task_ids,
    metric_temp_ids,
    metric_tbl
) {
  metric_lookup <- stats::setNames(metric_temp_ids, metric_tbl$metricName)
  source_lookup <- stats::setNames(metric_tbl$metricSourceType, metric_tbl$metricName)
  metric_key_lookup <- stats::setNames(metric_tbl$metricKey, metric_tbl$metricName)
  gist_url_lookup <- stats::setNames(metric_tbl$gist_url, metric_tbl$metricName)

  rows <- lapply(seq_along(evidence_names), function(i) {
    one_evidence_name <- evidence_names[[i]]
    one_task_temp_id <- evidence_task_ids[[i]]
    one_metric_names <- unique(trio$getMetrics(one_evidence_name))

    if (length(one_metric_names) == 0) {
      return(NULL)
    }

    data.frame(
      evidenceName = rep(one_evidence_name, length(one_metric_names)),
      task_temp_id = rep(one_task_temp_id, length(one_metric_names)),
      metric_temp_id = unname(metric_lookup[one_metric_names]),
      metricName = one_metric_names,
      metricSourceType = unname(source_lookup[one_metric_names]),
      metricKey = unname(metric_key_lookup[one_metric_names]),
      gist_url = unname(gist_url_lookup[one_metric_names]),
      stringsAsFactors = FALSE
    )
  })

  rows <- Filter(Negate(is.null), rows)
  if (length(rows) == 0) {
    return(data.frame(
      evidenceName = character(0),
      task_temp_id = character(0),
      metric_temp_id = character(0),
      metricName = character(0),
      metricSourceType = character(0),
      metricKey = character(0),
      gist_url = character(0),
      stringsAsFactors = FALSE
    ))
  }

  unique(do.call(rbind, rows))
}

private_submission_task_stage_choices <- function() {
  c("upstream", "intermediate", "downstream", "other")
}

private_submission_task_type_choices <- function(task_stage) {
  normalized_stage <- tolower(gsub("[^a-z]", "_", task_stage))
  normalized_stage <- gsub("_+", "_", normalized_stage)
  normalized_stage <- gsub("^_|_$", "", normalized_stage)

  switch(
    normalized_stage,
    upstream = c(
      "data_preprocessing",
      "signal_extraction",
      "read_alignment",
      "peak_calling",
      "feature_quantification",
      "molecule_counting",
      "cell_calling",
      "spectral_deconvolution",
      "quality_control",
      "doublet_detection",
      "normalisation",
      "batch_correction",
      "data_integration"
    ),
    intermediate = c(
      "dimensionality_reduction",
      "visualisation",
      "clustering",
      "cell_type_state_annotation",
      "differential_analysis",
      "copy_number_analysis",
      "variant_analysis",
      "mutation_analysis",
      "trajectory_inference",
      "pseudotime_analysis",
      "phylogenetic_analysis",
      "gene_program_analysis",
      "pathway_enrichment_analysis",
      "regulatory_network_inference",
      "chromatin_state_analysis",
      "cell_cell_communication_analysis",
      "multi_omics_integration"
    ),
    downstream = c(
      "cell_composition_analysis",
      "clonal_architecture_analysis",
      "lineage_tracing",
      "neighbourhood_analysis",
      "spatial_domain_detection",
      "microenvironment_analysis",
      "biomarker_discovery",
      "target_identification",
      "mechanism_inference",
      "disease_stratification",
      "patient_stratification"
    ),
    character(0)
  )
}

private_collect_submission_task_stage <- function(value = NULL, title) {
  choices <- private_submission_task_stage_choices()

  if (!is.null(value)) {
    value_chr <- private_submission_chr(value)
    if (!is.na(value_chr)) {
      if (value_chr %in% choices && !identical(value_chr, "other")) {
        return(value_chr)
      }
      if (!identical(value_chr, "other")) {
        return(value_chr)
      }
    }
  }

  if (!interactive()) {
    cli::cli_abort(
      "A value for {.val {title}} is required in non-interactive mode."
    )
  }

  selected <- utils::menu(choices, title = title)
  if (selected == 0) {
    cli::cli_abort("A selection for {.val {title}} is required.")
  }

  selected_value <- choices[[selected]]
  if (!identical(selected_value, "other")) {
    return(selected_value)
  }

  private_collect_submission_text(
    prompt = "Please specify the task stage",
    required = TRUE
  )
}

private_collect_submission_task_type <- function(
    value = NULL,
    task_stage,
    title,
    prompt
) {
  choices <- private_submission_task_type_choices(task_stage)

  if (!is.null(value)) {
    value_chr <- private_submission_chr(value)
    if (!is.na(value_chr)) {
      if (length(choices) == 0) {
        return(value_chr)
      }
      if (value_chr %in% choices) {
        return(value_chr)
      }
      if (!identical(value_chr, "other")) {
        return(value_chr)
      }
    }
  }

  if (!interactive()) {
    cli::cli_abort(
      "A value for {.val {title}} is required in non-interactive mode."
    )
  }

  if (length(choices) == 0) {
    return(private_collect_submission_text(
      prompt = prompt,
      required = TRUE
    ))
  }

  menu_choices <- c(choices, "other")
  selected <- utils::menu(menu_choices, title = title)
  if (selected == 0) {
    cli::cli_abort("A selection for {.val {title}} is required.")
  }

  selected_value <- menu_choices[[selected]]
  if (!identical(selected_value, "other")) {
    return(selected_value)
  }

  private_collect_submission_text(
    prompt = prompt,
    required = TRUE
  )
}

private_submission_dataset_name <- function(trio) {
  name <- private_submission_chr(trio$name)
  if (!is.na(name)) {
    return(name)
  }

  private_submission_chr(trio$dataSourceID)
}

private_prompt_with_default <- function(prompt, default = NULL, required = TRUE) {
  default_chr <- private_submission_chr(default)

  if (!interactive()) {
    if (!is.na(default_chr) || !required) {
      return(default_chr)
    }
    cli::cli_abort(
      "A value for {.val {prompt}} is required in non-interactive mode."
    )
  }

  prompt_text <- if (!is.na(default_chr)) {
    paste0(prompt, " [", default_chr, "]: ")
  } else {
    paste0(prompt, ": ")
  }

  entered <- readline(prompt_text)
  entered_chr <- private_submission_chr(entered)

  if (is.na(entered_chr)) {
    if (!is.na(default_chr)) {
      return(default_chr)
    }
    if (!required) {
      return(NA_character_)
    }
    cli::cli_abort("A value for {.val {prompt}} is required.")
  }

  entered_chr
}

private_inform_prepared_submission_files <- function(files) {
  if (is.null(files)) {
    return(invisible(NULL))
  }

  lines <- c()

  if (isTRUE(files$dataset$prepared) && !is.na(files$dataset$file)) {
    lines <- c(
      lines,
      "Prepared dataset file:",
      files$dataset$file
    )
  }

  if (isTRUE(files$evidence$prepared) && !is.na(files$evidence$file)) {
    lines <- c(
      lines,
      "",
      "Prepared evidence file:",
      files$evidence$file
    )
  }

  if (length(lines) > 0) {
    prepared_labels <- c(
      if (isTRUE(files$dataset$prepared)) "dataset" else character(0),
      if (isTRUE(files$evidence$prepared)) "supporting evidence" else character(0)
    )
    upload_note <- if (identical(prepared_labels, "supporting evidence")) {
      "Upload the supporting evidence file to Figshare, then continue with verification if needed."
    } else {
      "Upload these file(s) to the same Figshare article, then continue with verification if needed."
    }
    lines <- c(lines, "", upload_note)
    cli::cli_inform(lines)
  }

  invisible(NULL)
}

private_inform_submission_review <- function(submission, files = NULL, metric_info = NULL) {
  dataset_tbl <- submission$Dataset
  task_tbl <- submission$DatasetTask
  evidence_tbl <- submission$DatasetEvidence
  metric_tbl <- submission$Metric
  task_metric_tbl <- submission$DatasetTaskMetric

  gist_url <- NA_character_
  if (!is.null(metric_info) &&
      !is.null(metric_info$gist) &&
      !is.null(metric_info$gist$html_url)) {
    gist_url <- metric_info$gist$html_url
  } else if ("gist_url" %in% names(metric_tbl)) {
    gist_values <- unique(stats::na.omit(metric_tbl$gist_url))
    if (length(gist_values) > 0) {
      gist_url <- gist_values[[1]]
    }
  }

  dataset_source_id <- if ("datasourceID" %in% names(dataset_tbl)) {
    private_submission_chr(dataset_tbl$datasourceID[[1]])
  } else {
    NA_character_
  }
  evidence_source_ids <- if ("evidenceSourceID" %in% names(evidence_tbl)) {
    unique(stats::na.omit(evidence_tbl$evidenceSourceID))
  } else {
    character(0)
  }

  lines <- c(
    "Submission review summary:",
    paste0("  Dataset rows: ", nrow(dataset_tbl)),
    paste0("  Task rows: ", nrow(task_tbl)),
    paste0("  Evidence rows: ", nrow(evidence_tbl)),
    paste0("  Metric rows: ", nrow(metric_tbl)),
    paste0("  Task-metric rows: ", nrow(task_metric_tbl)),
    paste0("  Dataset source: ", private_submission_chr(dataset_tbl$source[[1]])),
    paste0("  Dataset source ID: ", dataset_source_id),
    paste0("  Task names: ", paste(task_tbl$taskName, collapse = ", ")),
    paste0("  Evidence names: ", paste(evidence_tbl$supportingEvidence, collapse = ", ")),
    paste0("  Metric names: ", paste(metric_tbl$metricName, collapse = ", "))
  )

  if (length(evidence_source_ids) > 0) {
    lines <- c(
      lines,
      paste0("  Evidence source IDs: ", paste(evidence_source_ids, collapse = ", "))
    )
  }

  if (!is.na(gist_url)) {
    lines <- c(lines, paste0("  Metric gist URL: ", gist_url))
  }

  if (!is.null(files)) {
    if (isTRUE(files$dataset$prepared) && !is.na(files$dataset$file)) {
      lines <- c(lines, paste0("  Prepared dataset file: ", files$dataset$file))
    }
    if (isTRUE(files$evidence$prepared) && !is.na(files$evidence$file)) {
      lines <- c(lines, paste0("  Prepared evidence file: ", files$evidence$file))
    }
  }

  cli::cli_inform(lines)
  invisible(NULL)
}

private_find_internal_metric_wrapper <- function(metric_name) {
  ns_exports <- getNamespaceExports("BenchHub")
  metric_exports <- ns_exports[grepl("metric$", ns_exports, ignore.case = TRUE)]

  candidates <- c(
    paste0(metric_name, "Metric"),
    paste0(metric_name, "metric")
  )
  candidates <- unique(candidates)

  for (candidate in candidates) {
    if (candidate %in% metric_exports) {
      return(candidate)
    }
  }

  normalized_target <- tolower(gsub("[^a-z0-9]", "", metric_name))
  normalized_exports <- tolower(gsub("[^a-z0-9]", "", sub("metric$", "", metric_exports, ignore.case = TRUE)))
  match_idx <- which(normalized_exports == normalized_target)

  if (length(match_idx) > 0) {
    return(metric_exports[[match_idx[[1]]]])
  }

  NA_character_
}

private_apply_prepared_files_to_submission <- function(submission, files) {
  if (!is.null(files$figshare$dataset)) {
    submission$Dataset$source[] <- files$figshare$dataset$source
    submission$Dataset$datasourceID[] <- files$figshare$dataset$sourceID
  } else if (!is.null(files$dataset)) {
    submission$Dataset$source[] <- private_submission_chr(files$dataset$source)
    submission$Dataset$datasourceID[] <- private_submission_chr(files$dataset$sourceID)
  }

  if (!is.null(files$figshare$evidence)) {
    submission$DatasetEvidence$evidenceSourceID[] <- files$figshare$evidence$sourceID
  }

  submission
}

private_collect_submission_choice <- function(value, choices, title) {
  if (!is.null(value) && !is.na(value) && nzchar(as.character(value))) {
    private_validate_submission_choice(value, title, choices)
    return(as.character(value))
  }

  if (!interactive()) {
    cli::cli_abort(
      "A value for {.val {title}} is required in non-interactive mode."
    )
  }

  selected <- utils::menu(choices, title = title)
  if (selected == 0) {
    cli::cli_abort("A selection for {.val {title}} is required.")
  }

  choices[[selected]]
}

private_collect_submission_text <- function(
    value = NULL,
    prompt,
    fallback = NULL,
    required = TRUE
) {
  if (!is.null(value)) {
    value_chr <- private_submission_chr(value)
    if (!is.na(value_chr) || !required) {
      return(value_chr)
    }
  }

  fallback_chr <- private_submission_chr(fallback)
  if (!is.na(fallback_chr)) {
    return(fallback_chr)
  }

  if (!interactive()) {
    if (required) {
      cli::cli_abort(
        "A value for {.val {prompt}} is required in non-interactive mode."
      )
    }
    return(NA_character_)
  }

  entered <- readline(paste0(prompt, ": "))
  entered_chr <- private_submission_chr(entered)

  if (required && is.na(entered_chr)) {
    cli::cli_abort("A value for {.val {prompt}} is required.")
  }

  entered_chr
}

private_collect_submission_vector <- function(
    value,
    n,
    arg,
    required = TRUE
) {
  if (is.null(value)) {
    return(rep(NA_character_, n))
  }

  if (length(value) == 1) {
    value <- rep(value, n)
  } else if (length(value) != n) {
    cli::cli_abort(c(
      "Invalid length for {.arg {arg}} defaults.",
      "i" = "Provide either one value or exactly {.val {n}} values."
    ))
  }

  value_chr <- as.character(value)
  if (required && any(is.na(value_chr) | !nzchar(value_chr))) {
    value_chr[is.na(value_chr) | !nzchar(value_chr)] <- NA_character_
  }

  value_chr
}
